parser: babel-eslint

plugins:
- prettier

extends:
- airbnb
- plugin:prettier/recommended

env:
  node: true
  browser: true

rules:

  prettier/prettier: [error, { singleQuote: true }]
  prettier/prettier.semi: false

  camelcase: off
  linebreak-style: off
  eqeqeq: [error, smart]
  no-dupe-keys: error
  no-return-assign: off
  consistent-return: off

  import/prefer-default-export: on
  import/no-extraneous-dependencies: off

  react/jsx-filename-extension: [error, { extensions: [.js] }]
  react/jsx-one-expression-per-line: off
  react/jsx-closing-bracket-location: off
  react/button-has-type: off
  react/no-unused-prop-types: off
  react/destructuring-assignment: off
  react/jsx-wrap-multilines: off
  react/prop-types: off
  react/no-unescaped-entities: [error, { forbid: ['>', '}'] }]
  react/array-type: false
  jsx-a11y/anchor-is-valid: [ error, {
    components: [ "Link" ],
    specialLink: [ "to", "hrefLeft", "hrefRight" ],
    aspects: [ "noHref", "invalidHref", "preferButton" ]
  }]

  jsx-a11y/label-has-for: off

  jsx-a11y/label-has-associated-control: [ 2, {
    labelComponents: ["label"],
    labelAttributes: ["htmlFor"],
    controlComponents: ["input"]
  }]

  no-plusplus: off
  radix: [error, "as-needed"]

